### ISSUE TITLE
Country field is often Unknown

### ISSUE THREAD

**Issue by ilyaglow** [jedisct1/iptoasn-webservice#3]
Hey there,

I noticed that while the service is perfectly suited for getting ASN from an IP (thanks for your great work!), the `Country` field often remains `Unknown` for no obvious reason.

As a possible solution your data may get merged with for example [maxmind geolite2 data](http://dev.maxmind.com/geoip/geoip2/geolite2/). It is free to use by anyone (sharealike licence). This is what I actually done as a workaround.

Cheers

**Comment by ilyaglow** [comment]
It seems that asian IPs are the most common endpoints that are `Unknown`.

For example if you'll try to lookup `113.172.7.100`:
```
{"announced":true,"as_country_code":"Unknown","as_description":"AS45899","as_number":45899,"first_ip":"113.172.0.0","ip":"113.172.7.100","last_ip":"113.172.31.255"}
```

Although APNIC says it's VN

**Comment by jedisct1** [comment]
Unfortunately ftp://ftp.apnic.net/pub/stats/apnic/delegated-apnic-latest doesn't have any information about AS45899 :(
