### ISSUE TITLE
Wrong country code for ip 94.31.34.46

### ISSUE THREAD

**Issue by vmalguy** [jedisct1/iptoasn-webservice#6]
I found an ip that has a wrong country code : 94.31.34.46

iptoasn say: 
`curl "https://api.iptoasn.com/v1/as/ip/94.31.34.46"`
`<th>AS Country code</th><td>US</td></tr><tr><th>AS Description</th><td>ZAYO-6461 - Zayo Bandwidth Inc</td>`	
 
Traceroute say UK:
` 1  vss-1b-6k.fr.eu (94.23.37.252)  67.549 ms  67.723 ms  67.889 ms
 2  10.95.68.130 (10.95.68.130)  0.188 ms  0.530 ms  0.695 ms
 3  10.95.66.72 (10.95.66.72)  0.328 ms  0.842 ms 10.95.66.66 (10.95.66.66)  1.006 ms
 4  10.95.64.2 (10.95.64.2)  1.278 ms 10.95.64.0 (10.95.64.0)  1.461 ms 10.95.64.2 (10.95.64.2)  1.631 ms
 5  be100-1041.ldn-1-a9.uk.eu (94.23.122.145)  4.371 ms  4.727 ms be100-1042.ldn-5-a9.uk.eu (213.251.130.103)  4.535 ms
 6  be100-2.ldn-1-a9.uk.eu (213.251.130.121)  5.052 ms ge-3-3-0.mpr1.lhr3.uk.above.net (195.66.236.76)  3.840 ms  4.393 ms`

Maxmind say Londres
`curl "https://www.maxmind.com/geoip/v2.1/city/94.31.34.46?use-downloadable-db=1&demo=0"`

`{"city":{"geoname_id":2643743,"names":{"es":"Londres","fr":"Londres","ja":"ロンドン","pt-BR":"Londres","ru":"Лондон","zh-CN":"伦敦","de":"London","en":"London"}},"continent":{"code":"EU","geoname_id":6255148,"names":{"fr":"Europe","ja":"ヨーロッパ","pt-BR":"Europa","ru":"Европа","zh-CN":"欧洲","de":"Europa","en":"Europe","es":"Europa"}},"country":{"iso_code":"GB","geoname_id":2635167,"names":{"ru":"Великобритания","zh-CN":"英国","de":"Vereinigtes Königreich","en":"United Kingdom","es":"Reino Unido","fr":"Royaume-Uni","ja":"イギリス","pt-BR":"Reino Unido"}},"location":{"accuracy_radius":20,"latitude":51.5092,"longitude":-0.0955,"time_zone":"Europe/London"},"postal":{"code":"EC4N"},"registered_country":{"iso_code":"GB","geoname_id":2635167,"names":{"ja":"イギリス","pt-BR":"Reino Unido","ru":"Великобритания","zh-CN":"英国","de":"Vereinigtes Königreich","en":"United Kingdom","es":"Reino Unido","fr":"Royaume-Uni"}},"subdivisions":[{"iso_code":"ENG","geoname_id":6269131,"names":{"de":"England","en":"England","es":"Inglaterra","fr":"Angleterre","ja":"イングランド","pt-BR":"Inglaterra","ru":"Англия","zh-CN":"英格兰"}}],"traits":{"autonomous_system_number":6461,"autonomous_system_organization":"Zayo Bandwidth Inc","domain":"above.net","isp":"Zayo Group EU Limited","organization":"Zayo Group EU Limited","ip_address":"94.31.34.46"}}%`

**Comment by jedisct1** [comment]
The closest announced route is 94.31.0.0/18, announced by AS6461 (Zayo Bandwidth).

This organization is in the US according to the ARIN : 

https://whois.arin.net/rest/asn/AS6461?s=AS6461
https://whois.arin.net/rest/org/ZAYOB.html

**Comment by vmalguy** [comment]
ok, I get it.
thanks !
