### ISSUE TITLE
124.43.127.12 always returns HTML

### ISSUE THREAD

**Issue by kozakvoj** [jedisct1/iptoasn-webservice#7]
If I ask for 124.43.127.12 address I always get an HTML (https://api.iptoasn.com/v1/as/ip/124.43.127.12). All other IP address I've tried return JSON instead.

**Comment by ilyaglow** [comment]
Self hosted version works as expected.

Looks like a caching issue.

**Comment by jedisct1** [comment]
That's what you get for forgetting the `Vary: Accept` header :)

Fixed in 811c41e27e368a772a1760e8486adeaf3c5aa84b, thanks!
