### ISSUE TITLE
using old data?

### ISSUE THREAD

**Issue by liyuling** [jedisct1/iptoasn-webservice#9]
Hi,

When I was checking 59.100.119.0, ip2asn shows it's AS63850

"
First IP	59.100.119.0
Last IP	59.100.119.7
AS Number	63850
AS Country code	AU
AS Description	ENTRUSTICT-AS-AP QRHUB PTY LTD T/A Entrust ICT
"

However other sources indicate AS2764.

If I do a whois on this IP, I got:

"
% Abuse contact for '59.100.119.0 - 59.100.119.7' is 'abuse@aapt.com.au'

inetnum:        59.100.119.0 - 59.100.119.7
netname:        QRHUBPTYLTD
descr:          QRHUB PTY LTD
country:        AU
admin-c:        GC1319-AP
tech-c:         GC1320-AP
status:         ASSIGNED NON-PORTABLE
mnt-by:         MAINT-AU-POWERTEL
mnt-irt:        IRT-AAPT-AU
last-modified:  2013-11-29T04:32:02Z
source:         APNIC

irt:            IRT-AAPT-AU
address:        AAPT Limited
address:        180-188 Burnley Street
address:        Richmond VIC 3121 AU
e-mail:         ipnoc@aapt.com.au
abuse-mailbox:  abuse@aapt.com.au
admin-c:        ANO2-AP
tech-c:         ANO2-AP
auth:           # Filtered
notify:         routing.shared@aapt.com.au
mnt-by:         MAINT-AU-AAPT
last-modified:  2017-10-22T23:39:00Z
source:         APNIC 
"

So I guess it should be "AAPT limited", which is AS2764?                            

Thanks

**Comment by jedisct1** [comment]
This is a route announced a couple minutes ago:

```
TABLE_DUMP2|1524585602|B|119.63.216.246|38883|59.100.119.0/29|38883 2764 63850|IGP|119.63.216.246|0|0|2764:65200 2764:65203 2764:65290 2764:65353 2764:65408 2764:65473 38883:2003|NAG||
```

AS63850 looks fine.

**Comment by jedisct1** [comment]
AS63850 is the origin of the 59.100.119.0/29 prefix.

It is way more specific than AS2764 that announces 59.100.0.0/15.
